2024-11-02 15:20:24,799 INFO: Retrieved 50 videos [in /Users/chrisbeaumont/Projects/YouTubeReports/youtube_utils.py:105]
2024-11-02 15:20:25,050 INFO: Retrieved 49 videos [in /Users/chrisbeaumont/Projects/YouTubeReports/youtube_utils.py:105]
2024-11-02 15:20:25,277 INFO: Retrieved 50 videos [in /Users/chrisbeaumont/Projects/YouTubeReports/youtube_utils.py:105]
2024-11-02 15:20:25,279 INFO: Total videos retrieved: 248 [in /Users/chrisbeaumont/Projects/YouTubeReports/youtube_utils.py:127]
2024-11-02 15:20:25,279 ERROR: Error in stream_analysis: name 'analyze_watch_history' is not defined [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:364]
2024-11-02 15:21:04,509 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:58]
2024-11-02 15:21:05,983 INFO: Starting OAuth callback processing [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:420]
2024-11-02 15:21:06,193 ERROR: Error in oauth2callback: (invalid_grant) Bad Request [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:461]
2024-11-02 15:21:06,194 ERROR: Exception traceback:  [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:462]
Traceback (most recent call last):
  File "/Users/chrisbeaumont/Projects/YouTubeReports/app.py", line 431, in oauth2callback
    flow.fetch_token(authorization_response=authorization_response)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/google_auth_oauthlib/flow.py", line 285, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 406, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Bad Request
2024-11-02 15:21:07,177 INFO: Initiating YouTube OAuth flow for user 1 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:401]
2024-11-02 15:21:07,178 INFO: Redirect URI: http://localhost:5000/auth/youtube/callback [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:402]
2024-11-02 15:21:07,178 INFO: State parameter: xtsohrvkjkx1QWCVorOgrJdhTxAF86 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:403]
2024-11-02 15:21:13,490 INFO: Starting OAuth callback processing [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:420]
2024-11-02 15:21:13,715 INFO: OAuth callback successful. Session ID: a5a361e3-08f5-45c6-8c0e-d57ed48f20cd [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:448]
2024-11-02 15:21:13,716 INFO: Credentials stored in session: True [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:449]
2024-11-02 15:21:13,721 INFO: Template rendered, returning response [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:457]
2024-11-02 15:21:14,990 INFO: Starting analysis stream for session a5a361e3-08f5-45c6-8c0e-d57ed48f20cd [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:300]
2024-11-02 15:21:14,991 INFO: Found credentials in session, starting analysis [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:310]
2024-11-02 15:21:15,004 INFO: Initialized YouTube API client [in /Users/chrisbeaumont/Projects/YouTubeReports/youtube_utils.py:92]
2024-11-02 15:21:15,340 INFO: Retrieved 50 videos [in /Users/chrisbeaumont/Projects/YouTubeReports/youtube_utils.py:105]
2024-11-02 15:21:15,567 INFO: Retrieved 49 videos [in /Users/chrisbeaumont/Projects/YouTubeReports/youtube_utils.py:105]
2024-11-02 15:21:15,803 INFO: Retrieved 50 videos [in /Users/chrisbeaumont/Projects/YouTubeReports/youtube_utils.py:105]
2024-11-02 15:21:16,047 INFO: Retrieved 49 videos [in /Users/chrisbeaumont/Projects/YouTubeReports/youtube_utils.py:105]
2024-11-02 15:21:16,233 INFO: Retrieved 50 videos [in /Users/chrisbeaumont/Projects/YouTubeReports/youtube_utils.py:105]
2024-11-02 15:21:16,234 INFO: Total videos retrieved: 248 [in /Users/chrisbeaumont/Projects/YouTubeReports/youtube_utils.py:127]
2024-11-02 15:22:39,572 INFO: Starting OAuth callback processing [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:420]
2024-11-02 15:22:39,765 ERROR: Error in oauth2callback: (invalid_grant) Bad Request [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:461]
2024-11-02 15:22:39,765 ERROR: Exception traceback:  [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:462]
Traceback (most recent call last):
  File "/Users/chrisbeaumont/Projects/YouTubeReports/app.py", line 431, in oauth2callback
    flow.fetch_token(authorization_response=authorization_response)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/google_auth_oauthlib/flow.py", line 285, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 406, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Bad Request
2024-11-02 15:22:40,612 INFO: Initiating YouTube OAuth flow for user 1 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:401]
2024-11-02 15:22:40,612 INFO: Redirect URI: http://localhost:5000/auth/youtube/callback [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:402]
2024-11-02 15:22:40,613 INFO: State parameter: MObJttOshDVYkzeZQIX07qh8WjGlXy [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:403]
2024-11-04 13:37:54,024 INFO: Initiating YouTube OAuth flow for user 2 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:401]
2024-11-04 13:37:54,030 INFO: Redirect URI: http://localhost:5000/auth/youtube/callback [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:402]
2024-11-04 13:37:54,038 INFO: State parameter: FhXzliNg17gWOnVxnefEwFgRY7zv6J [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:403]
2024-11-04 13:42:17,722 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:58]
2024-11-04 13:42:21,395 INFO: Starting /process_url endpoint [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:732]
2024-11-04 13:42:21,395 INFO: Received request data: {'url': 'https://www.youtube.com/@theschooloflifetv'} [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:736]
2024-11-04 13:42:21,395 INFO: Processing URL: https://www.youtube.com/@theschooloflifetv [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:744]
2024-11-04 13:42:21,395 INFO: Attempting to extract channel ID [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:748]
2024-11-04 13:42:21,780 INFO: Channel ID extraction result: UC7IcJI8PUf5Z3zKxnZvTBog [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:750]
2024-11-04 13:42:21,781 INFO: Processing URL as channel, Channel ID: UC7IcJI8PUf5Z3zKxnZvTBog [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:753]
2024-11-04 13:42:21,804 INFO: Existing report found: True [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:758]
2024-11-04 13:42:21,804 INFO: Found existing report for channel UC7IcJI8PUf5Z3zKxnZvTBog [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:761]
2024-11-04 13:42:21,809 INFO: Updating existing user access timestamp [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:778]
2024-11-04 13:42:21,866 INFO: Redirecting to: /dashboard?new_report=3 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:784]
2024-11-04 13:42:44,364 INFO: Starting /process_url endpoint [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:732]
2024-11-04 13:42:44,365 INFO: Received request data: {'url': 'https://www.youtube.com/@PaulDavids'} [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:736]
2024-11-04 13:42:44,365 INFO: Processing URL: https://www.youtube.com/@PaulDavids [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:744]
2024-11-04 13:42:44,365 INFO: Attempting to extract channel ID [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:748]
2024-11-04 13:42:44,728 INFO: Channel ID extraction result: UC_Oa7Ph3v94om5OyxY1nPKg [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:750]
2024-11-04 13:42:44,728 INFO: Processing URL as channel, Channel ID: UC_Oa7Ph3v94om5OyxY1nPKg [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:753]
2024-11-04 13:42:44,741 INFO: Existing report found: False [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:758]
2024-11-04 13:42:44,741 INFO: Fetching channel data for new report [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:792]
2024-11-04 13:43:13,012 INFO: Channel title: Paul Davids [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:802]
